app:
  port: 8089
  env: dev
  web:
    log:
      skip-path: /health,/swagger
      trace-name: X-Request-Id
    cors:
      origin:
      method:
      header:
      allow-credentials: true
      expose-header:
      max-age: 43200
mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: test
  parameters: charset=UTF8&parseTime=true&loc=Asia%2FShanghai
  pool:
    max-idle: 0
    max-open: 0
    max-life-time: 30m
    max-idle-time: 10m
  log:
    level: 4
    slow-log: 5s
    ignore-notfound: false
log:
  name: dio
  dir: ./logs
  max-age: 30
  debug: false
  std: true
  file: true
  trace-name: X-Request-Id
